# Generated by Django 3.0.5 on 2020-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=60, verbose_name='Estabelecimento')),
                ('cliente', models.CharField(max_length=14, verbose_name='Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
